# version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    # environment:
    #   OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:5000/v1/logs
    #   OTEL_EXPORTER_METRICS_OTEL_REST_ENDPOINT: http://localhost:5000/v1/metrics
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    configs:
      - source: otel-collector-config
        target: /etc/otel-collector-config.yaml
    depends_on:
      - loki
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    environment:
      - GF_INSTALL_PLUGINS=opentelemetry-collector-exporter
    # volumes: 
    #   - loki-data:/loki
    configs:
      - source: loki-config
        target: /config/config.yaml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      # - GF_LOKI_URL=http://loki:3100 # This is in the docs, but this does not work
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app,grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    configs:
    - source: grafana-datasources
      target: /usr/share/grafana/conf/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
    restart: unless-stopped
    # volumes:
    #   - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
  loki-data:
  otel-collector-data:  

configs:
  grafana-datasources:
    content: |
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
          minTimeRange: 1m
  loki-config:
    content: | 
      limits_config:
        allow_structured_metadata: true
  otel-collector-config:
    content: | 
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        # Collect own metrics
        prometheus:
          config:
            scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
              - targets: ['0.0.0.0:8888']
      exporters:
        debug:
          verbosity: detailed
        otlphttp/logs:
          endpoint: http://loki:3100/otlp
          #tls:
          #  insecure: true
      service:
        pipelines:
          traces:
            receivers: [otlp]
            exporters: [debug]
          metrics:
            receivers: [otlp, prometheus]
            exporters: [debug]
          logs:
            receivers: [otlp]
            exporters: [debug, otlphttp/logs]

